{% set version = "1.4.0" %}

package:
  name: pytest-console-scripts
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-console-scripts/pytest-console-scripts-{{ version }}.tar.gz
  sha256: 6335679ef013fa20402dfd5b07219877d874bd3f0a198b84b23f17897ccbe50a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - importlib-metadata >=3.6
    - pytest >=4.0.0
    - python >=3.7

test:
  source_files:
    - tests
  imports:
    - pytest_console_scripts
  commands:
    - pip check
    - pytest -vv --cov pytest_console_scripts -k "not test_env[subprocess]"
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/kvas-it/pytest-console-scripts
  summary: Pytest plugin for testing console scripts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - holgern
    - bollwyvl
