{% set name = "pytest-console-scripts" %}
{% set version = "0.1.5" %}
{% set sha256 = "d4e314e7fc481afb57f69432ed147120da32ce4a9673d00aca327a7e628e74d2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pytest >=3.0.0
    - mock >=2.0.0

test:
  imports:
    - pytest_console_scripts

about:
  home: https://github.com/kvas-it/pytest-console-scripts
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pytest plugin for testing console scripts'
  description: |
    Pytest-console-scripts is a Pytest plugin for testing python
    scripts installed via console_scripts entry point of setup.py.
    It can run the scripts under test in a separate process or using
    the interpreter that's running the test suite. The former mode
    ensures that the script will run in an environment that is
    identical to normal execution whereas the latter one allows
    much quicker test runs during development while simulating the
    real runs as much as possible.
  doc_url: https://github.com/kvas-it/pytest-console-scripts
  dev_url: https://github.com/kvas-it/pytest-console-scripts

extra:
  recipe-maintainers:
    - holgern
